config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root  'main#index'
  get   'login'  => 'main#login'
  post  'login'  => 'main#check_login'
  get   'logout' => 'main#logout'
  get   'company_report' => 'report#company_report'
  get   'contract_report' => 'report#contract_report'
  get   'lackinfo_report' => 'report#lackinfo_report'
  
  resources :stockholders do
    get 'archive', on: :collection
  end
  
  resources :companies do
    get 'archive', on: :collection
    resources :stocks, only: [:index]
  end
  
  resources :capital_increases, except: [:show] do
    get 'archive', on: :collection
  end
  
  resources :transactions, except: [:show] do
    get 'archive', on: :collection
  end
  
  resources :identities do
    resources :stocks, only: [:index]
  end
  
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    
    def login
        @show_error = params["show_error"]
    end
    
    def check_login
        puts params
        if params["account"] == "admin" and params["password"] == "admin"
            session[:name] = "admin"
            session[:is_admin] = true
            session[:is_login] = true
            redirect_to controller: 'main', action: 'index'    
        elsif params["account"] == "user" and params["password"] == "user"
            session[:name] = "employee"
            session[:is_admin] = false
            session[:is_login] = true
            redirect_to controller: 'main', action: 'index'    
        else
            redirect_to controller: 'main', action: 'login', show_error: true    
        end
    end
    
    def logout
        reset_session
        redirect_to controller: 'main', action: 'login'
    end
    
    def index
        @stockholders = Stockholder.not_deleted
        @companies = Company.not_deleted
    end

   
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/_error.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <div class="alert alert-danger" role="alert">
      Wrong account or password
    </div>
  </div>
</div>

app/views/main/index.html.erb
<div class="col-md-6 col-xs-12">
  <div class="card">
    <div class="my-row">
      <div class="col-xs-2 card-icon">
        <span class="glyphicon glyphicon-user" aria-hidden="true" style="margin-top: 30px"></span>
      </div>
      <div class="col-xs-10 card-content">
        <div class="my-row" style="margin: 10px 0px 10px 0px">
          <div class="col-xs-3" style="text-align: center">
            <strong style="font-size: 24px;">股東</strong>
          </div>

          <form action="stockholders" class="col-xs-9" style="padding: 0px">
            <div class="input-group">
              <select name="id" class="form-control select2">
                <% @stockholders.each do |s| %>
                  <option value="<%= s.id %>"><%= s.name_zh %><%= s.name_en %> / <%= s.passport %></option>
                <% end %>
              </select>
              <span class="input-group-btn">
                <button type="submit" class="btn btn-default">
                  <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </button>
              </span>
            </div>
          </form>
        </div>
        <hr class="no-margin">
        <div class="my-row">
          <a href="<%= new_stockholder_path %>" class="col-xs-4 card-btn">
            <h4><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> 新增</h4>
          </a>
          <a href="<%= stockholders_path %>" class="col-xs-4 card-btn card-center-btn">
            <h4><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> 列表</h4>
          </a>
          <a href="stockholders/archive" class="col-xs-4 card-btn">
            <h4><span class="glyphicon glyphicon glyphicon-trash" aria-hidden="true"></span> 封存</h4>
          </a>
        </div>
      </div>
    </div>
  </div>
  
  <div class="card">
    <div class="my-row">
      <div class="col-xs-2 card-icon">
        <span class="glyphicon glyphicon-briefcase" aria-hidden="true" style="margin-top: 30px"></span>
      </div>
      <div class="col-xs-10 card-content">
        <div class="my-row" style="margin: 10px 0px 10px 0px">
          <div class="col-xs-3" style="text-align: center">
            <strong style="font-size: 24px;">公司</strong>
          </div>
        
          <form action="companies" class="col-xs-9" style="padding: 0px">
            <div class="input-group">
              <select name="id" class="form-control select2">
                <% @companies.each do |c| %>
                  <option value="<%= c.id %>"><%= c.name_zh %></option>
                <% end %>
              </select>
              <span class="input-group-btn">
                <button type="submit" class="btn btn-default">
                  <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </button>
              </span>
            </div>
          </form>
        </div>
        <hr class="no-margin">
        <div class="my-row">
          <a href="<%= new_company_path %>" class="col-xs-4 card-btn">
            <h4><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> 新增</h4>
          </a>
          <a href="<%= companies_path %>" class="col-xs-4 card-btn card-center-btn">
            <h4><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> 列表</h4>
          </a>
          <a href="companies/archive" class="col-xs-4 card-btn">
            <h4><span class="glyphicon glyphicon glyphicon-trash" aria-hidden="true"></span> 封存</h4>
          </a>
        </div>
      </div>
    </div>
  </div>
  
  <div class="card">
    <div class="my-row">
      <div class="col-xs-2 card-icon">
        <span class="glyphicon glyphicon-list-alt" aria-hidden="true" style="margin-top: 67px"></span>
      </div>
      <div class="col-xs-10 card-content">
        <div class="my-row" style="margin: 10px 0px 10px 0px">
          <div class="col-xs-3" style="text-align: center">
            <strong style="font-size: 24px;">報表</strong>
          </div>
        </div>
        <hr class="no-margin">
        <a href="company_report">
          <div style="padding-left: 30px">
            <h4><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> 公司股數顯示表</h4>
          </div>
        </a>
        <hr class="no-margin">
        <a href="contract_report">
          <div style="padding-left: 30px">
            <h4><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> 合約進度表</h4>
          </div>
        </a>
        <hr class="no-margin">
        <a href="lackinfo_report">
          <div style="padding-left: 30px">
            <h4><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> 缺少資料表</h4>
          </div>
        </a>
         
      </div>
    </div>
  </div>
</div>

<div class="col-md-6 col-xs-12">
  <div class="card">
    <div class="my-row">
      <div class="col-xs-2 card-icon">
        <span class="glyphicon glyphicon-transfer" aria-hidden="true" style="margin-top: 30px"></span>
      </div>
      <div class="col-xs-10 card-content">
        <div class="my-row" style="margin: 10px 0px 10px 0px">
          <div class="col-xs-3" style="text-align: center">
            <strong style="font-size: 24px;">交易</strong>
          </div>
        </div>
        <hr class="no-margin">
        <div class="my-row">
          <a href="<%= new_transaction_path %>" class="col-xs-6 card-btn">
            <h4><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> 新增</h4>
          </a>
          <a href="<%= transactions_path %>" class="col-xs-6 card-btn card-center-btn" style="border-width: 0px 0px 0px 1px">
            <h4><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> 列表</h4>
          </a>
          </a>
        </div>
      </div>
    </div>
  </div>

  <div class="card">
    <div class="my-row">
      <div class="col-xs-2 card-icon">
        <span class="glyphicon glyphicon-usd" aria-hidden="true" style="margin-top: 30px"></span>
      </div>
      <div class="col-xs-10 card-content">
        <div class="my-row" style="margin: 10px 0px 10px 0px">
          <div class="col-xs-3" style="text-align: center">
            <strong style="font-size: 24px;">增資</strong>
          </div>
        </div>
        <hr class="no-margin">
        <div class="my-row">
          <a href="<%= new_capital_increase_path %>" class="col-xs-6 card-btn">
            <h4><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> 新增</h4>
          </a>
          
          <a href="<%= capital_increases_path %>" class="col-xs-6 card-btn card-center-btn" style="border-width: 0px 0px 0px 1px">
            <h4><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> 列表</h4>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag('main_index.js') %>

app/views/main/login.html.erb
<% if @show_error %>
  <%= render 'main/error' %>
<% end %>
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Login</h3>
      </div>
      <div class="panel-body">
        <%= form_tag "/login", method: "post" do %>
            <div class="form-group">
              <label>Account</label>
              <input type="text" class="form-control" name="account">
            </div>
            <div class="form-group">
              <label>Password</label>
              <input type="password" class="form-control" name="password">
            </div>
            <div class="form-group">
              <input class="btn btn-primary center-block" type="submit" value="Login">
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>