config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root  'main#index'
  get   'login'  => 'main#login'
  post  'login'  => 'main#check_login'
  get   'logout' => 'main#logout'
  get   'company_report' => 'report#company_report'
  get   'contract_report' => 'report#contract_report'
  get   'lackinfo_report' => 'report#lackinfo_report'
  
  resources :stockholders do
    get 'archive', on: :collection
  end
  
  resources :companies do
    get 'archive', on: :collection
    resources :stocks, only: [:index]
  end
  
  resources :capital_increases, except: [:show] do
    get 'archive', on: :collection
  end
  
  resources :transactions, except: [:show] do
    get 'archive', on: :collection
  end
  
  resources :identities do
    resources :stocks, only: [:index]
  end
  
end

app/models/stockholder.rb
class Stockholder < ActiveRecord::Base
  has_one :identity
  belongs_to :identity
  
  mount_uploader :copy_passport, PassportUploader
  mount_uploader :copy_signature, PassportUploader
  mount_uploader :copy_mail_addr, PassportUploader
  
  scope :deleted, -> { where("is_deleted=?", true)}
  scope :not_deleted, -> { where("is_deleted=?", false)}
  
  scope :filter_not_completed, -> { where(
    "  (copy_passport IS NULL)
    OR (copy_signature IS NULL)
    OR (copy_mail_addr IS NULL)"
  )}
  
  scope :filter_completed, -> { where.not(
    "  (copy_passport IS NULL)
    OR (copy_signature IS NULL)
    OR (copy_mail_addr IS NULL)"
  )}
  
  validates_presence_of :name_zh, :passport
  
end

app/controllers/stockholders_controller.rb
class StockholdersController < ApplicationController
  before_action :set_stockholder, :only => [:show, :edit, :update, :destroy]
  
  def index
    if params[:id]
      # GET /stockholders?id=#
      redirect_to stockholder_path(Stockholder.find(params[:id]))
    else
      @stockholders = Stockholder.not_deleted
      
      if params[:set_not_completed]
        @stockholders = @stockholders.filter_not_completed
      end
      
      if params[:set_completed]
        @stockholders = @stockholders.filter_completed
      end
    end
  end
  
  def create
    @stockholder = Stockholder.new(stockholder_params)
    if @stockholder.save
      @identity = Identity.create(:company_id => nil, :stockholder_id => @stockholder.id)
      @stockholder.update({:identity_id => @identity.id})
      
      flash[:saved] = "已儲存"
      redirect_to stockholder_path(@stockholder)
    else
      render :action => :new
    end
  end
  
  def new
    @stockholder = Stockholder.new
  end
  
  def edit
  end
  
  def show
    # 擁有股票
    @stocks =  @stockholder.identity.stock_show
    # 近期交易
    @transactions = @stockholder.identity.recent_transactions
  end
  
  def update
    if @stockholder.update(stockholder_params)
      flash[:saved] = "已儲存"
      redirect_to stockholder_path(@stockholder)
    else
      render :action => :edit
    end
  end
  
  # 封存
  def destroy
    @stockholder.update({is_deleted: true, date_deleted: DateTime.now.to_date})
    redirect_to stockholders_path
  end
  
  def archive
    @stockholders = Stockholder.deleted
  end
  
  
  private
  def set_stockholder
    @stockholder = Stockholder.find(params[:id])
  end
  
  def stockholder_params
    params.require(:stockholder).permit!
  end
  
end

app/helpers/stockholders_helper.rb
module StockholdersHelper
  def check_exist(is_exist)
    if is_exist
      return '<span class="glyphicon glyphicon-ok"></span>'.html_safe 
    else
      return '<span class="glyphicon glyphicon-remove"></span>'.html_safe 
    end
  end
end

app/views/stockholders/_form.html.erb
<%= form_for @stockholder do |f| %>
  
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">基本資料</div>
      <div class="panel-body">
        
        <div class="form-group">
          <%= f.label :name_zh, "中文姓名*" %>
          <%= f.text_field :name_zh, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <%= f.label :name_en, "英文姓名" %>
          <%= f.text_field :name_en, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <%= f.label :passport, "護照號碼*" %>
          <%= f.text_field :passport, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <%= f.label :country, "國籍" %>
          <%= f.text_field :country, class: "form-control" %>
        </div>
        
        <label>是否成年(年滿21歲)</label>
        <div class="checkbox" style="margin-top:8px">
          <label>
            <%= f.check_box :is21 %> 已成年
          </label>
        </div>
  
        <div class="form-group">
          <%= f.label :representative, "代理人" %>
          <%= f.text_field :representative, class: "form-control", placeholder: "請輸入代理人姓名" %>
          <span class="help-block">若未成年請填寫此欄</span>
        </div>
        
        <div class="form-group">
          <label for="stockholder_copy_passport">上傳護照影本</label>
          <%= f.file_field :copy_passport, class: "filestyle", "data-buttonText": "選擇檔案", "data-buttonBefore": "true" %>
        </div>
        <div class="form-group">
          <label for="stockholder_copy_signature">上傳簽名頁影本</label>
          <%= f.file_field :copy_signature, class: "filestyle", "data-buttonText": "選擇檔案", "data-buttonBefore": "true" %>
        </div>
        <div class="form-group">
          <label for="stockholder_copy_signature">上傳郵寄地址影本</label>
          <%= f.file_field :copy_mail_addr, class: "filestyle", "data-buttonText": "選擇檔案", "data-buttonBefore": "true" %>
        </div>
        
      </div>
    </div>
  </div>
  
  
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">聯絡方式</div>
      <div class="panel-body">
        
        <div class="form-group">
          <%= f.label :phone, "電話" %>
          <%= f.text_field :phone, class: "form-control"%>
        </div>
        
        <div class="form-group">
          <%= f.label :wechat, "微信" %>
          <%= f.text_field :wechat, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <%= f.label :address_zh, "郵寄地址 - 中文" %>
          <%= f.text_field :address_zh, class: "form-control"%>
        </div>
        
        <div class="form-group">
          <%= f.label :address_en, "郵寄地址 - 英文" %>
          <%= f.text_field :address_en, class: "form-control"%>
        </div>
          
        <div class="form-group">
          <%= f.label :email, "電子郵件" %>
          <%= f.text_field :email, class: "form-control" %>
        </div>
        
      </div>
    </div>
    
    <div class="panel panel-default">
      <div class="panel-heading">匯款帳號</div>
      <div class="panel-body">
        
        <div class="form-group">
          <%= f.label :account_bank, "匯出銀行" %>
          <%= f.text_field :account_bank, class: "form-control" %>
        </div>
          
        <div class="form-group">
          <%= f.label :account_num, "帳號" %>
          <%= f.text_field :account_num, class: "form-control" %>
        </div>
          
        <div class="form-group">
          <%= f.label :account_owner, "戶名" %>
          <%= f.text_field :account_owner, class: "form-control" %>
        </div>
            
        <div class="form-group">
          <%= f.label :account_owner_id, "身分證件號" %>
          <%= f.text_field :account_owner_id, class: "form-control" %>
        </div>
        
      </div>
    </div>
  </div>
  
  <%= f.submit "完成", class: "btn btn-default btn-primary col-md-12"%>

<% end %>

app/views/stockholders/archive.html.erb
<h1 class="page-header" style="margin-top: 0px">股東封存列表</h1>

<table class="table table-hover text-center">
  <thead>
    <tr>
   	  <th class="text-center">中文姓名</th>
   	  <th class="text-center">英文姓名</th>
   	  <th class="text-center">護照號碼</th>
   	  <th class="text-center">護照影本</th>
      <th class="text-center">簽名頁影本</th>
      <th class="text-center">郵寄地址影本</th>
      <th class="text-center">資料</th>
    </tr>
  </thead>
  <tbody>
    <% if @stockholders.size == 0 %>
      <tr><td colspan="7">無資料</td></tr>
    <% else %>
      <% @stockholders.each do |s| %>
        <tr>
       	  <td><%= s.name_zh %></td>
       	  <td><%= s.name_en %></td>
       	  <td><%= s.passport %></td>
       	  <td><%= check_exist(s.copy_passport?) %></td>
       	  <td><%= check_exist(s.copy_signature?) %></td>
       	  <td><%= check_exist(s.copy_mail_addr?) %></td>
       	  <td><%= link_to "Info", stockholder_path(s) , class: "btn btn-primary btn-xs" %></td>
       	</tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/stockholders/edit.html.erb
<h1 class="page-header" style="margin-top: 0px">編輯股東</h1>

<%= render :partial => "layouts/flash" %>

<%= render 'form' %>

app/views/stockholders/index.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="page-header" style="margin-top: 0px">股東列表</h1>
  </div>
  
  <h1>
    <div class="col-md-1">
      <%= link_to "全部", stockholders_path, {class: "btn btn-default col-md-12"} %>
    </div>
      <div class="col-md-1">
      <%= link_to "已完成", stockholders_path(:set_completed => 1), {class: "btn btn-default col-md-12"} %>
    </div>
    <div class="col-md-1">
      <%= link_to "未完成", stockholders_path(:set_not_completed => 1), {class: "btn btn-default col-md-12"} %>
    </div>
  </h1>
</div>

<%= render :partial => "layouts/flash" %>

<table class="table table-hover text-center">
  <thead>
    <tr>
   	  <th class="text-center">中文姓名</th>
   	  <th class="text-center">英文姓名</th>
   	  <th class="text-center">護照號碼</th>
   	  <th class="text-center">護照影本</th>
      <th class="text-center">簽名頁影本</th>
      <th class="text-center">郵寄地址影本</th>
      <th class="text-center">資料</th>
      <% if session[:is_admin] %>
      <th class="text-center">編輯</th>
      <th class="text-center">刪除</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% if @stockholders.blank? %>
      <tr><td colspan="9">無資料</td></tr>
      <% else %>
      <% @stockholders.each do |s| %>
        <tr>
       	  <td><%= s.name_zh %></td>
       	  <td><%= s.name_en %></td>
       	  <td><%= s.passport %></td>
       	  <td><%= check_exist(s.copy_passport?) %></td>
       	  <td><%= check_exist(s.copy_signature?) %></td>
       	  <td><%= check_exist(s.copy_mail_addr?) %></td>
       	  
       	  <td><%= link_to "Info", stockholder_path(s) , class: "btn btn-primary btn-xs" %></td>
       	  <% if session[:is_admin] %>
       	  <td><%= link_to "Edit", edit_stockholder_path(s) , class: "btn btn-success btn-xs" %></td>
       	  <td><%= button_to 'Del', stockholder_path(s), {method: "delete", class: "btn btn-danger btn-xs", data: {confirm: "確定刪除?"}} %></td>
       	  <% end %>
       	</tr>
      <% end %>

    <% end %>
  </tbody>
</table>

app/views/stockholders/new.html.erb
<h1 class="page-header" style="margin-top: 0px">新增股東</h1>

<%= render :partial => "layouts/flash" %>

<%= render 'form' %>

app/views/stockholders/show.html.erb
<div class="row">
  <% if !session[:is_admin] || @stockholder.is_deleted %>
    <div class="col-md-12">
      <h1 class="page-header" style="margin-top: 0px">
        <%= @stockholder.name_zh %> <%= @stockholder.name_en %>
        <% if @stockholder.is_deleted %>
           (已封存)
        <% end %>
      </h1>
    </div>
  <% else %>
    <div class="col-md-11">
      <h1 class="page-header" style="margin-top: 0px">
        <%= @stockholder.name_zh %> <%= @stockholder.name_en %>
      </h1>
    </div>
    <h1>
      <%= link_to "修改", edit_stockholder_path(@stockholder), class: "btn btn-default col-md-1" %>
    </h1>
  <% end %>
</div>

<%= render :partial => "layouts/flash" %>

<div class="well">
  <div class="row no-margin-top">
    <div class="col-md-4">
      <table class="table">
        <h3 class="no-margin-top"><strong>基本資料</strong></h3>
        <col width="120">
        <tr>
          <th>是否成年</th>
          <td>
            <% if @stockholder.is21? %>
              <input type="checkbox" id="is21" checked disabled readonly> 成年</input>
              &nbsp;&nbsp;&nbsp;
              <input type="checkbox" id="isnt21" disabled readonly> 未成年</input>
            <% else %>
              <input type="checkbox" id="is21" disabled readonly> 成年</input>
              &nbsp;&nbsp;&nbsp;
              <input type="checkbox" id="isnt21" checked disabled readonly> 未成年</input>
            <% end %>
          </td>
        </tr>
        <tr>
          <td>法定代理人</td>
          <td>
            <% if @stockholder.representative? %>
              <%= @stockholder.representative %>
            <% else %>
              N/A
            <% end %>
          </td>
        </tr>
        <tr>
          <th>護照號碼</th>
          <td><%= @stockholder.passport %></td>
        </tr>
        <tr>
          <th>國籍</th>
          <td><%= @stockholder.country %></td>
        </tr>
      </table>
        
      <table class="table">
        <h3><strong>聯絡方式</strong></h3>
        <col width="120">
        <tr>
          <th>電話</th>
          <td><%= @stockholder.phone %></td>
        </tr>
        <tr>
          <th>微信</th>
          <td><%= @stockholder.wechat %></td>
        </tr>
        <tr>
          <th>郵寄地址 - 中文</th>
          <td><%= @stockholder.address_zh %></td>
        </tr>
        <tr>
          <th>郵寄地址 - 英文</th>
          <td><%= @stockholder.address_en %></td>
        </tr>
        <tr>
          <th>電子信箱</th>
          <td><%= @stockholder.email %></td>
        </tr>
      </table>
      
      <table class="table">
        <h3><strong>匯款帳號</strong></h3>
        <col width="120">
        <tr>
          <th>匯出銀行</th>
          <td><%= @stockholder.account_bank %></td>
        </tr>
        <tr>
          <th>帳號</th>
          <td><%= @stockholder.account_num %></td>
        </tr>
        <tr>
          <th>戶名</th>
          <td><%= @stockholder.account_owner %></td>
        </tr>
        <tr>
          <th>身分證件號</th>
          <td><%= @stockholder.account_owner_id %></td>
        </tr>
      </table>
      
      <table class="table">
        <h3><strong>護照影本</strong></h3>
        <% if @stockholder.copy_passport.to_s == "" %>
          <p>未上傳</p>
        <% else %>
          <% if [".png", ".PNG", ".jpg", ".JPG", ".jpeg", ".JPEG"].include?(File.extname(@stockholder.copy_passport.to_s)) %>
            <%= image_tag @stockholder.copy_passport.to_s, {class: "img-responsive", height: "270", width: "360", alt: "護照影本", onclick: "setModal(this);"} %>
          <% else %>
            <a href="<%= @stockholder.copy_passport.to_s%>" target="_blank">
              <span class="glyphicon glyphicon-file" aria-hidden="true" style="font-size: 100px; color: #333333"></span>
              <p style="color: #333333"><%= URI.decode(File.basename(@stockholder.copy_passport.to_s)) %></p>  
            </a>
          <% end %>
        <% end %>      
      </table>
      
      <table class="table">
        <h3><strong>簽名頁影本</strong></h3>
        <% if @stockholder.copy_signature.to_s == "" %>
          <p>未上傳</p>
        <% else %>
          <% if [".png", ".PNG", ".jpg", ".JPG", ".jpeg", ".JPEG"].include?(File.extname(@stockholder.copy_signature.to_s)) %>
            <%= image_tag @stockholder.copy_signature.to_s, {class: "img-responsive", height: "270", width: "360", alt: "簽名頁影本", onclick: "setModal(this);"} %>
          <% else %>
            <a href="<%= @stockholder.copy_signature.to_s%>" target="_blank">
              <span class="glyphicon glyphicon-file" aria-hidden="true" style="font-size: 100px; color: #333333"></span>
              <p style="color: #333333"><%= URI.decode(File.basename(@stockholder.copy_signature.to_s)) %></p>  
            </a>
          <% end %>
        <% end %>
      </table>
      
      <table class="table">
        <h3><strong>郵寄地址影本</strong></h3>
        <% if @stockholder.copy_mail_addr.to_s == "" %>
          <p>未上傳</p>
        <% else %>
          <% if [".png", ".PNG", ".jpg", ".JPG", ".jpeg", ".JPEG"].include?(File.extname(@stockholder.copy_mail_addr.to_s)) %>
            <%= image_tag @stockholder.copy_mail_addr.to_s, {class: "img-responsive", height: "270", width: "360", alt: "簽名頁影本", onclick: "setModal(this);"} %>
          <% else %>
            <a href="<%= @stockholder.copy_mail_addr.to_s%>" target="_blank">
              <span class="glyphicon glyphicon-file" aria-hidden="true" style="font-size: 100px; color: #333333"></span>
              <p style="color: #333333"><%= URI.decode(File.basename(@stockholder.copy_mail_addr.to_s)) %></p>  
            </a>
          <% end %>
        <% end %>
      </table>
    </div>
    
    <div class="modal fade" id="image_modal" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <img src="" id="enlarge_image" class="img-responsive">
          </div>
        </div>
      </div>
    </div>
    
    <div class="col-md-8">
      <h3 class="no-margin-top"><strong>持有股票</strong></h3>
      <table class="table table-hover">
        <thead>
          <th>發行公司</th>
          <th>類別</th>
          <th>持有股數</th>
        </thead>
        <tbody>
          <% if @stocks.size == 0 %>
            <tr><td colspan="3">無資料</td></tr>
          <% else %>
            <% i = @stocks[:stock_info].size - 1 %>
            <% while i >= 0 %>
              <tr>
                <td><%= @stocks[:stock_info][i][:company_name] %></td>
                <td><%= @stocks[:stock_info][i][:stock_class] %></td>
                <td><%= @stocks[:stock_num][i] %></td>
              </tr>
              <% i = i - 1 %>
            <% end %>
          <% end %>
        </tbody>
      </table>

      <h3><strong>近期交易</strong></h3>
      <table class="table table-hover">
        <thead>
          <th>簽約日期</th>
          <th>買方</th>
          <th>賣方</th>
          <th>股票公司</th>
          <th>股票類型</th>
          <th>發行日期</th>
          <th>交易股數</th>
        </thead>
        <tbody>
          <% if @transactions.size == 0 %>
            <tr><td colspan="5">無資料</td></tr>
          <% else %>
            <% @transactions.each do |t| %>
              <tr>
                <td><%= t[:date_signed] %></td>
                <td><%= t[:buyer_name] %></td>
                <td><%= t[:seller_name] %></td>
                <td><%= t[:company_name] %></td>
                <td><%= t[:stock_class] %></td>
                <td><%= t[:date_issued] %></td>
                <td><%= t[:stock_num] %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= javascript_include_tag('setModal.js') %>