config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root  'main#index'
  get   'login'  => 'main#login'
  post  'login'  => 'main#check_login'
  get   'logout' => 'main#logout'
  get   'company_report' => 'report#company_report'
  get   'contract_report' => 'report#contract_report'
  get   'lackinfo_report' => 'report#lackinfo_report'
  
  resources :stockholders do
    get 'archive', on: :collection
  end
  
  resources :companies do
    get 'archive', on: :collection
    resources :stocks, only: [:index]
  end
  
  resources :capital_increases, except: [:show] do
    get 'archive', on: :collection
  end
  
  resources :transactions, except: [:show] do
    get 'archive', on: :collection
  end
  
  resources :identities do
    resources :stocks, only: [:index]
  end
  
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_one :identity
  belongs_to :identity
  belongs_to :stocks
  has_many :staffs
  has_many :capital_increases
  
  validates_presence_of :name_zh, 
    :date_establish,
    :fund,
    :stock_price,
    :stock_class,
    :currency,
    :stock_num
    
  validate :readonly_field, :on => :update
  validate :check_on_delete, :on => :update, :if => :is_deleted_changed?
  
  scope :deleted, -> { where("is_deleted=?", true)}
  scope :not_deleted, -> { where("is_deleted=?", false)}
  
  def stock_percentage
    capital_increases = CapitalIncrease.where("company_id=?", self.id)
    transactions = Transaction.where("company_id=?", self.id)
      .where("is_signed=?", true)
      .where("is_lacking=?", false)
    
    complete_hash = Hash.new
    complete_hash[self.identity_id] = {
      :name_zh => self.name_zh,
      :stock_num => 0,
      :percentage => 0 }
    capital_increases.each do |c|
      complete_hash[self.identity_id][:stock_num] += c.stock_num
    end
    total_stock_num = complete_hash[self.identity_id][:stock_num]
    
    transactions.each do |t|
      if not complete_hash.has_key? t.buyer_id
        complete_hash[t.buyer_id] = {
          :name_zh => Identity.find(t.buyer_id).self_detail.name_zh,
          :stock_num => 0,
          :percentage => 0 }
      end
      
      if not complete_hash.has_key? t.seller_id
        complete_hash[t.seller_id] = {
          :name_zh => Identity.find(t.seller_id).self_detail.name_zh,
          :stock_num => 0,
          :percentage => 0 }
      end
    end
    
    transactions.each do |t|
      complete_hash[t.buyer_id][:stock_num] += t.stock_num
      complete_hash[t.seller_id][:stock_num] -= t.stock_num
    end
    
    complete_tuple = complete_hash.values
    complete_tuple.each do |c|
      c[:percentage] = (c[:stock_num] / total_stock_num).round(5)
    end
    
    complete_tuple.sort_by! {|a| -a[:percentage]}
  end
  
  private
  def readonly_field
    self.errors.add(:fund, "READONLY") if self.fund_changed?
    self.errors.add(:currency, "READONLY") if self.currency_changed?
    self.errors.add(:stock_class, "READONLY") if self.stock_class_changed?
    self.errors.add(:stock_price, "READONLY") if self.stock_price_changed?
    self.errors.add(:stock_num, "READONLY") if self.stock_num_changed?
  end
  
  def check_on_delete
    capital_increases = CapitalIncrease.where("company_id=?", self.id)
    
    capital_increases.each do |c|
      c.update({is_deleted: true, date_deleted: DateTime.now.to_date})
    end
    
  end
  
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, :only => [:show, :edit, :update, :destroy]
  before_action :set_data, :only => [:new, :edit]

  def index
    if params[:id]
      # GET /companies?id=#
      redirect_to company_path(Company.find(params[:id]))
    else
      @companies = Company.not_deleted
    end
  end

  def create
    @company = Company.new(company_params)
    
    if @company.save
      
      # Create staffs
      if check_staff_params
        staff_params[:stockholder_id].length.times do |i|
          if not staff_params[:job_title][i].blank?
            Staff.create(:company_id => @company.id,
              :stockholder_id => staff_params[:stockholder_id][i],
              :job_title => staff_params[:job_title][i])
          end
        end
      end
      
      # Create identities
      @identity = Identity.create(:company_id => @company.id, :stockholder_id => nil)
      
      # Update identity_id
      @company.update({:identity_id => @identity.id})
      
      # Create capital increase
      @capital_increase = CapitalIncrease.create(
        :identity_id => @identity.id,
        :stock_class => @company.stock_class,
        :date_issued => @company.date_establish,
        :fund => @company.fund,
        :currency => @company.currency,
        :stock_price => @company.stock_price,
        :stock_num => @company.stock_num,
        :remark => "起始增資",
        :stock_checked => false,
        :is_first => true)
      
      redirect_to company_path(@company)
    else
      @staffs = Array.new
      if check_staff_params
        staff_params[:stockholder_id].length.times do |i|
          @staff = Staff.new({
            :stockholder_id => staff_params[:stockholder_id][i],
            :job_title => staff_params[:job_title][i]})
          @staffs.push(@staff)
        end
      end
      
      # set flash by error messages
      @company.errors.messages.each do |key, msg|
        if msg.first != "can't be blank"
          flash.now[key] = msg.first
        end
      end
      
      set_data()
      render :action => :new
    end
  end
  
  def new
    @company = Company.new
  end
  
  def edit
    @staffs = Staff.where("company_id=?", @company.id)
  end
  
  def show
    @stocks = @company.identity.stock_show
    @transactions = @company.identity.recent_transactions
    @capital_increases = @company.identity.recent_capital_increase
    @staffs = Staff.where("company_id=?", @company.id)
    @stock_percentage = @company.stock_percentage
  end
  
  def update
    if @company.update(company_params)
      if check_staff_params
        Staff.where("company_id=?", @company.id).destroy_all
        
        staff_params[:stockholder_id].length.times do |i|
          if(staff_params[:job_title][i] != "")
            Staff.create(:company_id => @company.id,
              :stockholder_id => staff_params[:stockholder_id][i],
              :job_title => staff_params[:job_title][i])
          end
        end
      end
      
      redirect_to company_path(@company)
    else
      @staffs = Array.new
      staff_params[:stockholder_id].length.times do |i|
        @staff = Staff.new({
          :stockholder_id => staff_params[:stockholder_id][i],
          :job_title => staff_params[:job_title][i]})
        @staffs.push(@staff)
      end
      
      # set flash by error messages
      @company.errors.messages.each do |key, msg|
        puts msg
        if msg.first != "can't be blank"
          flash.now[key] = msg.first
        end
      end
      
      set_data()
      render :action => :edit
    end
  end
  
  # 封存
  def destroy
    @company.update({is_deleted: true, date_deleted: DateTime.now.to_date})
    redirect_to companies_path
  end

  
  private
  def set_company
    @company = Company.find(params[:id])
  end
  
  def set_data
    @stockholders = Stockholder.all
    @bank_hashes = [
      {'title'=> '匯款帳戶資訊 - 美金',
       'bank' => :us_account_bank,
       'num'  => :us_account_num,
       'name' => :us_account_name,
       'address' => :us_account_bank_addr},
      {'title'=> '匯款帳戶資訊 - 人民幣',
       'bank' => :cn_account_bank,
       'num'  => :cn_account_num,
       'name' => :cn_account_name,
       'address' => :cn_account_bank_addr},
      {'title'=> '匯款帳戶資訊 - 台幣',
       'bank' => :tw_account_bank,
       'num'  => :tw_account_num,
       'name' => :tw_account_name,
       'address' => :tw_account_bank_addr}]
  end
    
  def company_params
    params.require(:company).permit!
  end
  
  def staff_params
    params.permit(:staff)
  end
  
  def check_staff_params
    # no staff
    if staff_params.blank?
      return false
    end
    
    if staff_params[:stockholder_id].length != staff_params[:job_title].length
      return false
    end
    
    return true
  end
 
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>
  
  <div class="row">
    <!-- 公司基本資料 -->
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">公司基本資料</h3>
        </div>
        <div class="panel-body">
          <div class="form-group">
            <%= f.label :name_zh, "中文名稱" %>
            <%= f.text_field :name_zh, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :name_en, "英文名稱" %>
            <%= f.text_field :name_en, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :ein, "公司稅號" %>
            <%= f.text_field :ein, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :phone, "公司電話" %>
            <%= f.text_field :phone, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :address, "公司地址" %>
            <%= f.text_field :address, class: 'form-control' %>
          </div>
        </div>
      </div>
    </div>
    <!-- 日期 --> 
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">日期資訊</h3>
        </div>
        <div class="panel-body">
          <div class="form-group">
            <%= f.label :date_establish, "公司成立日期" %>
            <div class='input-group date' id='datetimepicker1'>
              <%= f.text_field :date_establish , class: 'form-control' %>
              <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
              </span>
            </div>
            <span class="help-block no-margin-bottom">等於起始股票發行日期</span>
          </div>
    
          <div class="form-group">
            <%= f.label :date_accounting, "會計年度" %>
            <div class='input-group date' id='datetimepicker2'>
              <%= f.text_field :date_accounting , class: 'form-control' %>
              <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- 資本額 -->
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">起始資金</h3>
        </div>
        <div class="panel-body">
          <div class="form-group">
            <%= f.label :stock_class, "股票類別" %>
            <% if @company.new_record? %>
              <%= f.text_field :stock_class, class: 'form-control' %>
            <% else %>
              <%= f.text_field :stock_class, class: 'form-control', readonly: true %>
            <% end %>
          </div>
          <div class="form-group">
            <%= f.label :fund, "資本額" %>
            <% if @company.new_record? %>
              <%= f.text_field :fund, class: 'form-control auto-calculate'%>
            <% else %>
              <%= f.text_field :fund, class: 'form-control', readonly: true %>
            <% end %>
          </div>
          <div class="form-group">
            <%= f.label :currency, "幣別" %>
            <% if @company.new_record? %>
              <%= f.select :currency, Currency.types, {}, { :class => 'form-control' } %>
            <% else %>
              <%= f.text_field :currency, class: 'form-control', readonly: true %>
            <% end %>
          </div>
          <div class="form-group">
            <%= f.label :stock_price, "每股面額" %>
            <% if @company.new_record? %>
              <%= f.text_field :stock_price, class: 'form-control auto-calculate'%>
            <% else %>
              <%= f.text_field :stock_price, class: 'form-control', readonly: true %>
            <% end %>
          </div>
          <div class="form-group">
            <%= f.label :stock_num, "原始股數" %>
            <% if @company.new_record? %>
              <%= f.text_field :stock_num, class: 'form-control' %>
            <% else %>
              <%= f.text_field :stock_num, class: 'form-control', readonly: true %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <!-- 帳戶資訊 -->
  <div class="row">
    <% @bank_hashes.each_with_index  do |bank_hash, index| %>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><%= bank_hash['title'] %></h3>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <%= f.label bank_hash['bank'], "銀行名稱" %>
              <%= f.text_field bank_hash['bank'] , class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label bank_hash['num'], "帳號" %>
              <%= f.text_field bank_hash['num'] , class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label bank_hash['name'], "帳戶名稱" %>
              <%= f.text_field bank_hash['name'] , class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label bank_hash['address'], "銀行地址" %>
              <%= f.text_field bank_hash['address'] , class: 'form-control' %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  
  <!-- 公司人員 -->
  <button type="button" id="add_btn" class="btn btn-primary" style="margin-bottom: 16px">新增公司人員</button>
  <div id="staff_zone" class="row" style="margin-top: 0px">
    <% if @staffs != nil %>
      <% @staffs.each do |f| %>
        <div id="first_staff" class="col-md-4" style="margin-bottom: 16px">
          <div class="panel panel-default" style="margin-bottom: 4px">
            <div class="panel-heading">
              <h3 class="panel-title">公司人員</h3>
            </div>
            <div class="panel-body">
              <div class="form-group">
                <label>職稱</label>
                <input type="text" name="staff[job_title][]" class="form-control" value="<%= f.job_title %>">
              </div>
              <div class="form-group">
                <label>員工</label>
                <select class="staff_select2" style="width: 100%" name="staff[stockholder_id][]">
                  <% @stockholders.each do |s| %>
                    <% if s.id == f.stockholder_id %>
                      <option value="<%= s.id %>" selected="selected"><%= s.name_zh %></option>
                    <% else %>
                      <option value="<%= s.id %>"><%= s.name_zh %></option>
                    <% end %>                
                  <% end %>
                </select>
              </div>
            </div>
          </div>
          <button type="button" id="remove_btn" class="remove_btn btn btn-dangerbtn-sm">移除</button>
        </div>
      <% end %>
    <% end %>
  </div>
  
  <div class="row">
    <%= f.submit "完成", class: 'btn btn-default btn-primary col-md-12' %>
  </div>
<% end %>

<script>
  $(function() {
    $('#add_btn').click(function() {
      var staff_form_str =
        '<div id="first_staff" class="col-md-4" style="margin-bottom: 16px">'+
          '<div class="panel panel-default" style="margin-bottom: 4px">'+
            '<div class="panel-heading">'+
              '<h3 class="panel-title">公司人員</h3>'+
            '</div>'+
            '<div class="panel-body">'+
              '<div class="form-group">'+
                '<label>職稱</label>'+
                '<input type="text" name="staff[job_title][]" class="form-control">'+
              '</div>'+
                '<div class="form-group">'+
                '<label>員工</label>'+
                '<select class="staff_select2" style="width: 100%" name="staff[stockholder_id][]">'+
                <% @stockholders.each do |s| %>
                  '<option value=<%= s.id%>><%= s.name_zh%></option>'+
                <% end %>
                '</select>'+
              '</div>'+
            '</div>'+
          '</div>'+
          '<button type="button" id="remove_btn" class="remove_btn btn btn-danger btn-sm">移除</button>'
        '</div>'
      
      var staff_form = $('<div/>').html(staff_form_str);
      staff_form.find(".staff_select2").select2({theme: "bootstrap"})
      staff_form.find("#remove_btn").click(function() {
        $(this).parent().remove();
      });
      $("#staff_zone").append(staff_form);
    });  
  });
</script>

app/views/companies/archive.html.erb
<h1 class="page-header" style="margin-top: 0px">公司封存列表</h1>

<%= render :partial => "layouts/flash" %>

<table class="table table-hover text-center">
  <thead>
    <tr>
   	  <th class="text-center">中文名稱</th>
   	  <th class="text-center">英文名稱</th>
   	  <th class="text-center">稅號</th>
   	  <th class="text-center">電話</th>
      <th class="text-center">地址</th>
      <th class="text-center">成立日期</th>
      <th class="text-center">會計年度</th>
      <th class="text-center">資料</th>
    </tr>
  </thead>
  <tbody>
    <% if @companies.blank? %>
      <tr><td colspan="8">無資料</td></tr>
      <% else %>
      <% @companies.each do |s| %>
        <tr>
       	  <td><%= s.name_zh %></td>
       	  <td><%= s.name_en %></td>
       	  <td><%= s.ein %></td>
       	  <td><%= s.phone %></td>
       	  <td><%= s.address %></td>
       	  <td><%= s.date_establish %></td>
      	  <td><%= s.date_accounting %></td>
       	  <td><%= link_to "Info", company_path(s) , class: "btn btn-primary btn-xs" %></td>
       	</tr>
      <% end %>

    <% end %>
  </tbody>
</table>

app/views/companies/edit.html.erb
<h1 class="page-header" style="margin-top: 0px">編輯公司</h1>

<%= render :partial => "layouts/flash" %>

<%= render 'form' %>

<%= javascript_include_tag('company_form.js') %>

app/views/companies/index.html.erb
<h1 class="page-header" style="margin-top: 0px">公司列表</h1>

<%= render :partial => "layouts/flash" %>

<table class="table table-hover text-center">
  <thead>
    <tr>
   	  <th class="text-center">中文名稱</th>
   	  <th class="text-center">英文名稱</th>
   	  <th class="text-center">稅號</th>
   	  <th class="text-center">電話</th>
      <th class="text-center">地址</th>
      <th class="text-center">成立日期</th>
      <th class="text-center">會計年度</th>
      <% if session[:is_admin] %>
      <th class="text-center">資料</th>
      <th class="text-center">編輯</th>
      <th class="text-center">刪除</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% if @companies.blank? %>
      <tr><td colspan="10">無資料</td></tr>
      <% else %>
      <% @companies.each do |s| %>
        <tr>
       	  <td><%= s.name_zh %></td>
       	  <td><%= s.name_en %></td>
       	  <td><%= s.ein %></td>
       	  <td><%= s.phone %></td>
       	  <td><%= s.address %></td>
       	  <td><%= s.date_establish %></td>
      	  <td><%= s.date_accounting %></td>

       	  <td><%= link_to "Info", company_path(s) , class: "btn btn-primary btn-xs" %></td>
       	  <% if session[:is_admin] %>
       	  <td><%= link_to "Edit", edit_company_path(s) , class: "btn btn-success btn-xs" %></td>
       	  <td><%= button_to 'Del', company_path(s), {method: "delete", class: "btn btn-danger btn-xs", data: {confirm: "確定刪除?"}} %></td>
       	  <% end %>
       	</tr>
      <% end %>

    <% end %>
  </tbody>
</table>

app/views/companies/new.html.erb
<h1 class="page-header" style="margin-top: 0px">新增公司</h1>

<%= render :partial => "layouts/flash" %>

<%= render 'form' %>

<%= javascript_include_tag('company_form.js') %>

app/views/companies/show.html.erb
<div class="row">
  <% if !session[:is_admin] || @company.is_deleted %>
    <div class="col-md-12">
      <h1 class="page-header" style="margin-top: 0px">
        <%= @company.name_zh %> <%= @company.name_en %>
        <% if @company.is_deleted %>
           (已封存)
        <% end %>
      </h1>
    </div>
  <% else %>
    <div class="col-md-11">
      <h1 class="page-header" style="margin-top: 0px">
        <%= @company.name_zh %> <%= @company.name_en %>
      </h1>
    </div>
    <h1>
      <%= link_to "修改", edit_company_path(@company), class: "btn btn-default col-md-1" %>
    </h1>
  <% end %>
</div>

<div class="well">
  <div class="row" style="margin-top: 0px">
    <div class="col-md-6">
      <h3><strong>公司資料</strong></h3>
      <table class="table">
        <col width="250">
        <tr>
          <th>稅號</th>
          <td><%= @company.ein %></td>
        </tr>
        <tr>
          <th>電話</th>
          <td><%= @company.phone %></td>
        </tr>
        <tr>
          <th>地址</th>
          <td><%= @company.address %></td>
        </tr>
        <tr>
          <th>成立日期</th>
          <td><%= @company.date_establish %></td>
        </tr>
        <tr>
          <th>年度會計日</th>
          <td><%= @company.date_accounting %></td>
        </tr>
      </table>
    </div>
    <div class="col-md-6">
      <h3><strong>起始資金</strong></h3>
      <table class="table">
        <col width="250">
        <tr>
          <th>資本額</th>
          <td><%= @company.fund %></td>
        </tr>
        <tr>
          <th>幣別</th>
          <td><%= Currency.types[@company.currency-1][0] %></td>
        </tr>
        <tr>
          <th>股票類別</th>
          <td><%= @company.stock_class %></td>
        </tr>
        <tr>
          <th>每股面額</th>
          <td><%= @company.stock_price %></td>
        </tr>
        <tr>
          <th>股票數量</th>
          <td><%= @company.stock_num %></td>
        </tr>
      </table>
    </div>
  </div>

  <h3 style="margin-top: 20px"><strong>匯款帳戶資訊</strong></h3>
  <table class="table">
    <col width="150">
    <col width="316">
    <col width="316">
    <col width="316">
    <thead>
      <th class="caption_style"></th>
      <th class="caption_style">美金銀行</th>
      <th class="caption_style">人民幣銀行</th>
      <th class="caption_style">新台幣銀行</th>
    </thead>
    <tbody>
      <tr>
        <th>銀行名稱</th>
        <td><%= @company.us_account_bank %></td>
        <td><%= @company.cn_account_bank %></td>
        <td><%= @company.tw_account_bank %></td>
      </tr>
      <tr>
        <th>帳號</th>
        <td><%= @company.us_account_num %></td>
        <td><%= @company.cn_account_num %></td>
        <td><%= @company.tw_account_num %></td>
      </tr>
      <tr>
        <th>戶名</th>
        <td><%= @company.us_account_name %></td>
        <td><%= @company.cn_account_name %></td>
        <td><%= @company.tw_account_name %></td>
      </tr>
      <tr>
        <th>銀行地址</th>
        <td><%= @company.us_account_bank_addr %></td>
        <td><%= @company.cn_account_bank_addr %></td>
        <td><%= @company.tw_account_bank_addr %></td>
      </tr>
    </tbody>
  </table>
  
  <h3 style="margin-top: 20px"><strong>公司人員</strong></h3>
  <table class="table">
    <col width="10">
    <col width="200">
    <thead>
      <th>職稱</th>
      <th>姓名</th>
    </thead>
    <tbody>
      <% @staffs.each do |s| %>
      <tr>
        <td><%= s.job_title %></td>
        <td><%= Stockholder.find(s.stockholder_id).name_zh %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  
  <h3 class="margin-top: 20px" style="display: inline-block"><strong>股東</strong></h3> <span class="help-block" style="display: inline-block">交易完成之持股</span>
  <table class="table table-hover">
    <thead>
      <th>股東</th>
      <th>持有股數</th>
      <th>占比</th>
    </thead>
    <% if @stock_percentage.size == 0 %>
      <tr><td colspan="3">無資料</td></tr>
    <% else %>
      <% @stock_percentage.each do |s| %>
        <tr>
          <% if s[:percentage] >= 0.95 %>
            <td><strong><%= s[:name_zh] %> *</strong></td>
            <td><strong><%= s[:stock_num] %></strong></td>
            <td><strong><%= s[:percentage] %></strong></td>
          <% else %>
            <td><%= s[:name_zh] %></td>
            <td><%= s[:stock_num] %></td>
            <td><%= s[:percentage] %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </table>
  
  <h3 class="margin-top: 20px" style="display: inline-block"><strong>持股</strong></h3> <span class="help-block" style="display: inline-block">包括未完成交易之持股</span>
  <table class="table table-hover">
    <thead>
      <th>發行公司</th>
      <th>類別</th>
      <th>持有股數</th>
    </thead>
    <% if @stocks.size == 0 %>
      <tr><td colspan="3">無資料</td></tr>
    <% else %>
      <% i = @stocks[:stock_info].size - 1 %>
      <% while i >= 0 %>
        <tr>
          <td><%= @stocks[:stock_info][i][:company_name] %></td>
          <td><%= @stocks[:stock_info][i][:stock_class] %></td>
          <td><%= @stocks[:stock_num][i] %></td>
        </tr>
        <% i = i - 1 %>
      <% end %>
    <% end %>
  </table>
  
  <h3 class="margin-top: 20px"><strong>近期交易</strong></h3>
  <table class="table table-hover">
    <thead>
      <th>買方</th>
      <th>賣方</th>
      <th>股票公司</th>
      <th>股票類型</th>
      <th>交易股數</th>
    </thead>
    <% if @transactions.size == 0 %>
      <tr><td colspan="5">無資料</td></tr>
    <% else %>
      <% @transactions.each do |t| %>
        <tr>
          <td><%= t[:buyer_name] %></td>
          <td><%= t[:seller_name] %></td>
          <td><%= t[:company_name] %></td>
          <td><%= t[:stock_class] %></td>
          <td><%= t[:stock_num] %></td>
        </tr>
      <% end %>
    <% end %>
  </table>
    
  <h3 class="margin-top: 20px"><strong>近期增資</strong></h3>
  <table class="table table-hover">
    <thead>
      <th>股票類型</th>
      <th>生效日期</th>
      <th>金額</th>
      <th>每股面額</th>
      <th>總股數</th>
    </thead>
    <% if @capital_increases.size == 0 %>
      <tr><td colspan="5">無資料</td></tr>
    <% else %>
      <% @capital_increases.each do |t| %>
        <tr>
          <td><%= t[:stock_class] %></td>
          <td><%= t[:date_issued] %></td>
          <td><%= t[:fund] %></td>
          <td><%= t[:stock_price] %></td>
          <td><%= t[:stock_num] %></td>
        </tr>
      <% end %>
    <% end %>
  </table>
      
</div>