config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root  'main#index'
  get   'login'  => 'main#login'
  post  'login'  => 'main#check_login'
  get   'logout' => 'main#logout'
  get   'company_report' => 'report#company_report'
  get   'contract_report' => 'report#contract_report'
  get   'lackinfo_report' => 'report#lackinfo_report'
  
  resources :stockholders do
    get 'archive', on: :collection
  end
  
  resources :companies do
    get 'archive', on: :collection
    resources :stocks, only: [:index]
  end
  
  resources :capital_increases, except: [:show] do
    get 'archive', on: :collection
  end
  
  resources :transactions, except: [:show] do
    get 'archive', on: :collection
  end
  
  resources :identities do
    resources :stocks, only: [:index]
  end
  
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, :only => [:edit, :update, :destroy, :delete]
  layout 'fluid_application', :only => :index
  
  def index
    set_data()
    @identities = Hash.new
    @company_names = Hash.new
    @stocks = Array.new
    @transactions = Transaction.all.not_deleted
    @capital_increases = CapitalIncrease.all
    
    if params[:buyer_id].present? && params[:buyer_id] != "0"
      @transactions = @transactions.buyer_id(params[:buyer_id])
    end
    if params[:seller_id].present? && params[:seller_id] != "0"
      @transactions = @transactions.seller_id(params[:seller_id])
    end
    if params[:company_id].present? && params[:stock_class].present? && params[:date_issued].present?
      if params[:company_id] != "undefined" && params[:stock_class] != "undefined" && params[:date_issued] != "undefined"
        @transactions = @transactions.stock(params[:company_id], params[:stock_class], params[:date_issued])
      end
    end
    if params[:set_completed]
      @transactions = @transactions.filter_completed
    elsif params[:set_not_completed]
      @transactions = @transactions.filter_not_completed
    end
    @transactions = @transactions.sort_by{|t| t[:date_signed]}.reverse
    
    @capital_increases.each do |c_i|
      set_stock(c_i)
    end
    
    @transactions.each do |t|
      set_identity(t.seller_id)
      set_identity(t.buyer_id)
      set_company_name(t.company_id)
    end
  end
  
  def create
    if params[:transaction].key?(:stock)
      stock_hash = JSON.parse params[:transaction][:stock]
      stock_hash.delete("id")
      @transaction = Transaction.new(stock_hash.merge(transaction_params))
    else
      @transaction = Transaction.new(transaction_params)
    end
    
    if @transaction.save
      flash[:saved] = "已儲存"
      redirect_to edit_transaction_path(@transaction)
    else
      # set flash by error messages
      @transaction.errors.messages.each do |key, msg|
        if msg.first != "can't be blank"
          flash.now[key] = msg.first
        end
      end
      
      set_data()
      render :action => :new
    end
  end
 
  def new
    set_data()
    @transaction = Transaction.new
  end
  
  def edit
    set_data()
  end
  
  def update
    if @transaction.update(transaction_params)
      flash[:saved] = "已儲存"
      redirect_to edit_transaction_path(@transaction)
    else
      @transaction.errors.messages.each do |key, msg|
        if msg.first != "can't be blank"
          flash.now[key] = msg.first
        end
      end
      set_data()
      render :action => :edit
    end
  end
  
  def destroy
    if not @transaction.destroy
      # set flash by error messages
      @transaction.errors.messages.each do |key, msg|
        if msg.first != "can't be blank"
          flash.now[key] = msg.first
        end
      end
    end
      
    redirect_to transactions_path
  end
  
  # 封存
  def delete
    if not @capital_increase.update({is_deleted: true, date_deleted: DateTime.now.to_date})
      # set flash by error messages
      @capital_increase.errors.messages.each do |key, msg|
        if msg.first != "can't be blank"
          flash.now[key] = msg.first
        end
      end
    end
    
    redirect_to capital_increases_path
  end
  
  
  private
  def set_transaction
    @transaction = Transaction.find(params[:id])
  end
  
  def set_data
    @companies = Company.not_deleted
    @stockholders = Stockholder.not_deleted
  end
  
  def transaction_params
    params.require(:transaction).except(:stock).permit!
  end

  def set_identity(identity_id)
    if !@identities.has_key?(identity_id)
      @identities[identity_id] = Identity.find(identity_id).self_detail
    else 
      return
    end
  end
  
  def set_company_name(company_id)
    if !@company_names.has_key?(company_id)
      @company_names[company_id] = Company.find(company_id).name_zh
    else 
      return
    end
  end
  
  def set_stock(capital_increase)
    if capital_increase.stock_num > 0
      @stocks.push({
        :company_id => capital_increase.company.id,
        :company_name => capital_increase.company.name_zh,
        :stock_class => capital_increase.stock_class,
        :date_issued => capital_increase.date_issued
      })
    end
  end
  
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def status_check(is_need, is_exist)
    if is_need
      if is_exist
        return '<span class="glyphicon glyphicon-ok"></span>'.html_safe 
      else
        return '<span class="glyphicon glyphicon-remove"></span>'.html_safe 
      end
    else
      return '<span class="glyphicon glyphicon-minus"></span>'.html_safe 
    end
  end
end

app/views/transactions/_form.html.erb
<%= form_for @transaction, html: { id: :transaction_form } do |f| %>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">交易明細</div>
      <div class="panel-body">
        
        <div class="form-group">
          <%= f.label :buyer_id, "買方*" %>
          <% if @transaction.new_record? %>
            <%= f.select :buyer_id, options_for_select(@companies.map{ |c| [c.name_zh, c.identity.id]} + @stockholders.map{ |s| [s.name_zh + " / " + s.passport, s.identity.id]}), {}, {class: "form-control bootstrap_select2"} %>
          <% else %>
            <input class="form-control" value="<%= Identity.find(@transaction.buyer_id).self_detail.name_zh %>" readonly >
          <% end %>
        </div>
        <div class="form-group">
          <%= f.label :seller_id, "賣方*" %>
          <% if @transaction.new_record? %>
            <%= f.select :seller_id, options_for_select(@companies.map{ |c| [c.name_zh, c.identity.id]} + @stockholders.map{ |s| [s.name_zh + " / " + s.passport, s.identity.id]}), {}, {class: "form-control bootstrap_select2"} %>
          <% else %>
            <input class="form-control" value="<%= Identity.find(@transaction.seller_id).self_detail.name_zh %>" readonly >
          <% end %>
        </div>
        <div class="form-group">
          <%= f.label :stock, "股票*" %>
          <% if @transaction.new_record? %>
            <select class="form-control" name="transaction[stock]" id="transaction_stock"></select>
          <% else %>
            <input class="form-control" value="<%= Company.find(@transaction.company_id).name_zh %> / <%= @transaction.stock_class %> / <%= @transaction.date_issued %>" readonly >
          <% end %>
          <span class="help-block no-margin-bottom">發行公司 / 股票類別 / 發行日期</span>
        </div>
        
        <div class="form-group">
          <div class="row">
            <div class="col-md-6">
              <%= f.label :fund_original, "投資金額" %>
              <% if @transaction.new_record? %>
                <%= f.text_field :fund_original, class: "form-control calculate-fund" %>
              <% elsif @transaction.fund_original.nil? %>
                <%= f.text_field :fund_original, class: "form-control" %>
              <% else %>
                <input class="form-control" value="<%= @transaction.fund_original %>" readonly >
              <% end %>
            </div>
            <div class="col-md-6">
              <%= f.label :currency_original, "幣別" %>
              <% if @transaction.new_record? or @transaction.currency_original.nil? %>
                <%= f.select :currency_original, Currency.types, {}, { class: 'form-control' } %>
              <% else %>
                <input class="form-control" value="<%= Currency.types[@transaction.currency_original-1][0] %>" readonly >
              <% end %>
            </div>
          </div>
        </div>
  
        <div class="form-group">
          <div class="row">
            <div class="col-md-6">
              <%= f.label :exchange_rate, "匯率" %>
              <% if @transaction.new_record? %>
                <%= f.text_field :exchange_rate, {class: "form-control calculate-fund", value: 1} %>
              <% else %>
                <%= f.text_field :exchange_rate, {class: "form-control"} %>
              <% end %>
            </div>
            <div class="col-md-6">
              <%= f.label :date_paid, "匯率轉換日" %>
              <% if @transaction.new_record? or @transaction.date_paid.nil? %>
                <div class="input-group date" id="transaction_datetimepicker1">
                  <%= f.text_field :date_paid , class: "form-control" %>
                  <span class="input-group-addon">
                      <span class="glyphicon glyphicon-calendar"></span>
                  </span>
                </div>
              <% else %>
                <input class="form-control" value="<%= @transaction.date_paid %>" readonly>
              <% end %>
            </div>
          </div>
        </div>
        
        <div class="form-group">
          <div class="row">
            <div class="col-md-6">
              <%= f.label :fund, "交易金額*" %>
              <% if @transaction.new_record? %>
                <%= f.text_field :fund, class: "form-control calculate-stocknum" %>
              <% else %>
                <%= f.text_field :fund, {class: 'form-control', readonly: true} %>
              <% end %>
              <span class="help-block no-margin-bottom">投資金額 / 匯率</span>
            </div>
            <div class="col-md-6">
              <%= f.label :currency, "認定幣別" %>
              <%= f.hidden_field :currency %>
              <% if @transaction.new_record? %>
                <input class="form-control currency" readonly>
              <% else %>
                <input class="form-control" value="<%= Currency.types[@transaction.currency-1][0] %>" readonly>
              <% end %>
              <span class="help-block no-margin-bottom">由股票發行公司決定</span>
            </div>
          </div>
        </div>
        
        <div class="form-group">
          <div class="row">
            <div class="col-md-6">
              <%= f.label :stock_price, "每股價格*" %>
              <% if @transaction.new_record? %>
                <%= f.text_field :stock_price, class: "form-control calculate-stocknum" %>
              <% else %>
                <input class="form-control" value="<%= @transaction.stock_price %>" readonly>
              <% end %>
            </div>
            <div class="col-md-6">
              <%= f.label :currency, "認定幣別" %>
              <% if @transaction.new_record? %>
                <input class="form-control currency" readonly>
              <% else %>
                <input class="form-control" value="<%= Currency.types[@transaction.currency-1][0] %>" readonly>
              <% end %>
              <span class="help-block no-margin-bottom">由股票發行公司決定</span>
            </div>
          </div>  
        </div>    
        
        <div class="form-group">  
          <%= f.label :stock_num, "交易股數*" %>
          <% if @transaction.new_record? %>
            <%= f.text_field :stock_num, class: "form-control" %>
          <% else %>
            <input class="form-control" value="<%= @transaction.stock_num %>" readonly>
          <% end %>
        </div>
          
        <div class="form-group">
          <%= f.label :date_signed, "合約生效日*" %>
          <% if @transaction.new_record? %>
            <div class="input-group date" id="transaction_datetimepicker2">
              <%= f.text_field :date_signed , class: "form-control" %>
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
              </span>
            </div>
          <% else %>
            <input class="form-control" value="<%= @transaction.date_signed %>" readonly>
          <% end %>
        </div>
        
        <div class="form-group">
          <%= f.label :remark, "備註" %>
          <%= f.text_area :remark, {class: 'form-control', rows: 5} %>
        </div>
        
      </div>
    </div>
  </div>
  
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">檔案上傳區</div>
      <div class="panel-body">
        <div class="form-group">
          <label>
            <%= f.check_box :contract_0_needed %> 意向書
          </label>
          <%= f.file_field :contract_0, class: "filestyle", "data-buttonText": "", "data-buttonBefore": "true" %>
        </div>
        <%= render :partial => "transactions/image", :locals => { :contract => @transaction.contract_0.to_s } %>
            
        <div class="form-group">
          <label>
            <%= f.check_box :contract_1_needed %> Regular S
          </label>
          <%= f.file_field :contract_1, class: "filestyle", "data-buttonText": "", "data-buttonBefore": "true" %>
        </div>
        <%= render :partial => "transactions/image", :locals => { :contract => @transaction.contract_1.to_s } %>
      
        <div class="form-group">
          <label>
            <%= f.check_box :contract_2_needed %> 中文股份買賣合約 - 美金
          </label>
          <%= f.file_field :contract_2, class: "filestyle", "data-buttonText": "", "data-buttonBefore": "true" %>
        </div>
        <%= render :partial => "transactions/image", :locals => { :contract => @transaction.contract_2.to_s } %>
        
        <div class="form-group">
          <label>
            <%= f.check_box :contract_3_needed %> 中文股份買賣合約 - 人民幣
          </label>
          <%= f.file_field :contract_3, class: "filestyle", "data-buttonText": "", "data-buttonBefore": "true" %>
        </div>
        <%= render :partial => "transactions/image", :locals => { :contract => @transaction.contract_3.to_s } %>
        
        <div class="form-group">
          <label>
            <%= f.check_box :contract_4_needed %> Share Purchase Agreement
          </label>
          <%= f.file_field :contract_4, class: "filestyle", "data-buttonText": "", "data-buttonBefore": "true" %>
        </div>
        <%= render :partial => "transactions/image", :locals => { :contract => @transaction.contract_4.to_s } %>
        
        <div class="form-group">
          <label>
            <%= f.check_box :contract_5_needed %> W-8 Ben
          </label>
          <%= f.file_field :contract_5, class: "filestyle", "data-buttonText": "", "data-buttonBefore": "true" %>
        </div>
        <%= render :partial => "transactions/image", :locals => { :contract => @transaction.contract_5.to_s } %>
        
        <div class="form-group">
          <label>
            <%= f.check_box :contract_6_needed %> 換股協議書
          </label>
          <%= f.file_field :contract_6, class: "filestyle", "data-buttonText": "", "data-buttonBefore": "true" %>
        </div>
        <%= render :partial => "transactions/image", :locals => { :contract => @transaction.contract_6.to_s } %>
        
        <div class="form-group">
          <label>
            <%= f.check_box :contract_7_needed %> 聲明書
          </label>
          <%= f.file_field :contract_7, class: "filestyle", "data-buttonText": "", "data-buttonBefore": "true" %>
        </div>
        <%= render :partial => "transactions/image", :locals => { :contract => @transaction.contract_7.to_s } %>
        
        <div class="form-group">
          <%= f.label :contract_8, "銀行水單" %>
          <%= f.file_field :contract_8, class: "filestyle", "data-buttonText": "", "data-buttonBefore": "true", "multiple": "true" %>
        </div>
        <% if @transaction.contract_8.to_s != "" %>
          <% @transaction.contract_8.each do |c_8| %>
            <%= render :partial => "transactions/image", :locals => { :contract => c_8.to_s } %>
          <% end %>
        <% end %>
        
        <div class="form-group">
          <%= f.label :remark_contract, "合約備註" %>
          <%= f.text_area :remark_contract, {class: 'form-control', rows: 5} %>
        </div>
        
      </div>
    </div>
  </div>
    
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">其他</div>
      <div class="panel-body">   
      
        <div class="form-group">
          <%= f.label :signed_buyer, "簽署日期 - 買方" %>
          <div class="input-group date" id="transaction_datetimepicker3">
            <%= f.text_field :signed_buyer , class: "form-control" %>
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
          <span class="help-block no-margin-bottom">未簽署請留白</span>
        </div>
        
        <div class="form-group">
          <%= f.label :signed_seller, "簽署日期 - 賣方" %>
          <div class="input-group date" id="transaction_datetimepicker4">
            <%= f.text_field :signed_seller , class: "form-control" %>
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
          <span class="help-block no-margin-bottom">未簽署請留白</span>
        </div>
        
        <div class="form-group">
          <%= f.label :send_buyer, "合約郵寄日期 - 買方" %>
          <div class="input-group date" id="transaction_datetimepicker5">
            <%= f.text_field :send_buyer , class: "form-control" %>
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
          <span class="help-block no-margin-bottom">未寄送請留白</span>
        </div>
        
        <div class="form-group">
          <%= f.label :send_seller, "合約郵寄日期 - 賣方" %>
          <div class="input-group date" id="transaction_datetimepicker6">
            <%= f.text_field :send_seller , class: "form-control" %>
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
          <span class="help-block no-margin-bottom">未寄送請留白</span>
        </div>
        
        <div class="form-group">
          <%= f.label :is_printed, "資料是否列印" %>
          <br/>
          <label>
            <%= f.check_box :is_printed %> 已列印
          </label>
        </div>
  
      </div>
    </div>

    <%= f.submit "完成", {class: "btn btn-default btn-primary col-md-12"}%>
  </div>

<% end %>

<!--picture display-->
<div class="modal fade" id="image_modal" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <img src="" id="enlarge_image" class="img-responsive">
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag('setModal.js') %>
<%= javascript_include_tag('transaction_form.js') %>

app/views/transactions/_image.erb
<% if contract != "" %>
  <div class="form-group" style="text-align:center">
    <!--image file-->
    <% if [".png", ".PNG", ".jpg", ".JPG", ".jpeg", ".JPEG"].include?(File.extname(contract)) %>
      <%= image_tag contract, {class: "img-responsive", onclick: "setModal(this);"} %>
    <!--document file-->
    <% else %>
      <a href="<%= contract%>" target="_blank">
        <span class="glyphicon glyphicon-file" aria-hidden="true" style="font-size: 100px; color: #333333"></span>
        <p style="color: #333333"><%= URI.decode(File.basename(contract)) %></p>  
      </a>
    <% end %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1 class="page-header" style="margin-top: 0px">編輯交易</h1>

<%= render :partial => "layouts/flash" %>

<%= render 'form' %>

app/views/transactions/index.html.erb
<%= render :partial => 'layouts/flash' %>

<div class="row col-md-offset-1" style="margin-top: 0px">
  
  <div class="col-md-2">
    <div class="btn-group" style="float: right">
      <a href="" id="set_all" class="btn btn-default">全部</a>
      <a href="" id="set_completed" class="btn btn-default">已完成</a>
      <a href="" id="set_not_completed" class="btn btn-default">未完成</a>
    </div>
  </div>
  
  <div class="col-md-2" style="padding-left: 0px; display: table">
    <select id="buyer_filter_input" class="form-control bootstrap_select2" style="display: table-cell">
      <option value="0">買方</option>
      <optgroup label="股東">
      <% @stockholders.each do |s| %>
        <option value="<%= s.identity_id %>"><%= s.name_zh %></option>
      <% end %>
      <optgroup label="公司">
      <% @companies.each do |c| %>
        <option value="<%= c.identity_id %>"><%= c.name_zh %></option>
      <% end %>
    </select>
  </div>
  <div class="col-md-2" style="padding-left: 0px; display: table">
    <select id="seller_filter_input" class="form-control bootstrap_select2" style="display: table-cell">
      <option value="0">賣方</option>
      <optgroup label="股東">
      <% @stockholders.each do |s| %>
        <option value="<%= s.identity_id %>"><%= s.name_zh %></option>
      <% end %>
      <optgroup label="公司">
      <% @companies.each do |c| %>
        <option value="<%= c.identity_id %>"><%= c.name_zh %></option>
      <% end %>
    </select>
  </div>
  <div class="col-md-3" style="padding-left: 0px; display: table">
    <select id="stock_filter_input" class="form-control bootstrap_select2" style="display: table-cell">
      <option value="0">股票</option>
      <% @stocks.each do |s| %>
        <option value="{'company_id': '<%= s[:company_id] %>', 'stock_class': '<%= s[:stock_class] %>', 'date_issued': '<%= s[:date_issued] %>'}">
          <%= s[:company_name] %> / <%= s[:stock_class] %> / <%= s[:date_issued] %>
        </option>
      <% end %>
    </select>
  </div>
  
  <a href="" id="filter_btn" class="btn btn-default">
    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
  </a>
  
</div>
<div class="row" style="margin-left: 0px; margin-right: 0px; margin-top:30px">
<table class="table table-hover text-center">
  <thead>
    <tr>
      <th class="text-center" style="font-size: 0.5em;">交易日期</th>
   	  <th class="text-center" style="font-size: 0.5em;">買方</th>
   	  <th class="text-center" style="font-size: 0.5em;">賣方</th>
   	  <th class="text-center" style="font-size: 0.5em;">股票</th>
   	  <th class="text-center" style="font-size: 0.5em;">股數</th>
      <th class="text-center" style="font-size: 0.5em;" width="60px" >意向書</th>
      <th class="text-center" style="font-size: 0.5em;" width="60px" >Regular S</th>
   	  <th class="text-center" style="font-size: 0.5em;" width="60px" >USD合約</th>
   	  <th class="text-center" style="font-size: 0.5em;" width="60px" >RMB合約</th>
   	  <th class="text-center" style="font-size: 0.5em;" width="60px" >購買協議</th>
   	  <th class="text-center" style="font-size: 0.5em;" width="60px" >W8BEN</th>
   	  <th class="text-center" style="font-size: 0.5em;" width="60px" >換股協議</th>
   	  <th class="text-center" style="font-size: 0.5em;" width="60px" >聲明書</th>
   	  <th class="text-center" style="font-size: 0.5em;" width="60px" >銀行水單</th>
   	  <th class="text-center" style="font-size: 0.5em;" width="60px" >合約寄買方</th>
   	  <th class="text-center" style="font-size: 0.5em;" width="60px" >合約寄賣方</th>
   	  <% if session[:is_admin] %>
   	  <th class="text-center" style="font-size: 0.5em" width="60px" >編輯</th>
   	  <th class="text-center" style="font-size: 0.5em" width="60px" >刪除</th>
   	  <% end %>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each do |t| %>
    <tr>
      <td style="white-space: nowrap"><%= t.date_signed %></td>
   	  <td style="white-space: nowrap">
   	    <% if @identities[t.buyer_id].class.name == "Stockholder" %>
   	    <%= link_to @identities[t.buyer_id].name_zh, stockholder_path(@identities[t.buyer_id]) %>
   	    <% elsif @identities[t.buyer_id].class.name == "Company" %>
   	    <%= link_to @identities[t.buyer_id].name_zh, company_path(@identities[t.buyer_id]) %>
   	    <% end %>
   	  </td>
   	  <td style="white-space: nowrap">
   	    <% if @identities[t.seller_id].class.name == "Stockholder" %>
   	    <%= link_to @identities[t.seller_id].name_zh, stockholder_path(@identities[t.seller_id]) %>
   	    <% elsif @identities[t.seller_id].class.name == "Company" %>
   	    <%= link_to @identities[t.seller_id].name_zh, company_path(@identities[t.seller_id]) %>
   	    <% end %>
   	  </td>
   	  <td style="white-space: nowrap"><%= @company_names[t.company_id] %> / <%= t.stock_class %> / <%= t.date_issued %></td>
   	  <td style="white-space: nowrap"><%= t.stock_num %></td>
   	  
   	  <td><%= status_check(t.contract_0_needed, t.contract_0?) %></td>
   	  <td><%= status_check(t.contract_1_needed, t.contract_1?) %></td>
   	  <td><%= status_check(t.contract_2_needed, t.contract_2?) %></td>
   	  <td><%= status_check(t.contract_3_needed, t.contract_3?) %></td>
   	  <td><%= status_check(t.contract_4_needed, t.contract_4?) %></td>
   	  <td><%= status_check(t.contract_5_needed, t.contract_5?) %></td>
   	  <td><%= status_check(t.contract_6_needed, t.contract_6?) %></td>
   	  <td><%= status_check(t.contract_7_needed, t.contract_7?) %></td>
   	  <td><%= status_check(true, t.contract_8?) %></td>
   	  
   	  <td>
   	    <% if t.send_buyer? %>
   	      <%= t.send_buyer %>
   	    <% else %>  
   	      <span class="glyphicon glyphicon-remove"></span>
   	    <% end %>
   	  </td>
   	  <td>
   	    <% if t.send_seller? %>
   	      <%= t.send_seller %>
   	    <% else %>  
   	      <span class="glyphicon glyphicon-remove"></span>
   	    <% end %>
   	  </td>
      <% if session[:is_admin] %>
   	  <td><%= link_to 'Edit', edit_transaction_path(t), class: "btn btn-success btn-xs" %></td>
   	  <td><%= button_to 'Del', transaction_path(t), {method: "delete", class: "btn btn-danger btn-xs", data: {confirm: "確定刪除?"}} %></td>
   	  <% end %>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

<%= javascript_include_tag('transaction_index.js') %>

app/views/transactions/new.html.erb
<h1 class="page-header" style="margin-top: 0px">新增交易</h1>

<%= render :partial => "layouts/flash" %>

<%= render 'form' %>